# Generated by Django 4.2.2 on 2023-06-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='encryption_key',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='download_code',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
