# Generated by Django 4.2.2 on 2023-06-18 21:38

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_file_encryption_key_alter_file_download_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='download_code',
            field=models.CharField(default=app.models.generate_uuid, max_length=36, unique=True),
        ),
    ]
