# Generated by Django 4.2.2 on 2023-06-29 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_file_encryption_key_sharedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='users_with_access',
            field=models.ManyToManyField(null=True, related_name='shared_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
