# Generated by Django 4.2.2 on 2023-06-29 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_file_users_with_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='users_with_access',
        ),
        migrations.AddField(
            model_name='file',
            name='shared_with_users',
            field=models.ManyToManyField(related_name='shared_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SharedFile',
        ),
    ]
